### ISSUE TITLE
BK is now also a content type?

### ISSUE THREAD

**Issue by Eworm** [Eworm/big-kahuna#14]
Looks like it replaced the collections. Doesn't sound right.

<img width="205" alt="schermafbeelding 2018-12-09 om 22 30 12" src="https://user-images.githubusercontent.com/511488/49703169-0b07e100-fc02-11e8-9f3c-1f7c6f6d4a92.png">

**Comment by Eworm** [comment]
I didn't switch to the 1.3 branch. I'll try that.

**Comment by Eworm** [comment]
* I switched to the 1.3 branch
* Did gulp just to be sure
* And it's still there. I also checked in FF just to be sure, and it's the same.

**Comment by Eworm** [comment]
Could this maybe have something to do with switching from a fieldtype?

**Comment by zacksmash** [comment]
I don't think so. Are you sure you don't have a Collection called "Big Kahuna burger"? I don't see that anywhere in the code or anything. The fact that it has "burger" in the name leads me to believe it's something you've added manually.

**Comment by Eworm** [comment]
I'll check!

**Comment by zacksmash** [comment]
Closing this as I don’t think it’s a big. Let me know if you get it in a fresh install.
