### ISSUE TITLE
Overflow issue with the filter list

### ISSUE THREAD

**Issue by zacksmash** [Eworm/big-kahuna#16]
If the filter list has quite a lot of items in it, it creates a large space at the bottom of the page. It also creates a weird page jump when clicking on checkboxes to add items to a menu.

Steps to reproduce:
1) Add a lot of pages/entries (around 30-40)
2) Visit the BK Menu Edit page
3) Scroll down and see the big space at the bottom or click on a checkbox to see the page jump

**Comment by Eworm** [comment]
Yeah, I think that's a chrome bug. FF doesn't add the extra space.
