### ISSUE TITLE
Organizing Pages/Posts in the filter menu

### ISSUE THREAD

**Issue by zacksmash** [Eworm/big-kahuna#2]
As a site grows with a lot of Posts/Entries, the filter menu becomes a little tough to work through, even with the search bar. Let's chat about how we can make the filter system a little more robust.

**Comment by Eworm** [comment]
The problem is that pages don't have a collectionName(), which still sounds strange to me.

**Comment by Eworm** [comment]
I did it! The word pages is also in the path, which I can use to filter pages. Done!

**Comment by zacksmash** [comment]
I'll have to check this out! Good stuff!

**Comment by zacksmash** [comment]
I am getting this error when I try it out.

![screen shot 2018-12-10 at 3 14 11 pm](https://user-images.githubusercontent.com/6118407/49765001-494ae200-fc8e-11e8-9f50-97ebb2e358ec.png)

**Comment by Eworm** [comment]
Try again?

**Comment by zacksmash** [comment]
Boom! Looks great!

Quick note: If I type "Blog" it'll return all blog entries and anything that has "blog" in it's title, even if it's not a blog entry. Is this expected?
![screen shot 2018-12-10 at 3 22 55 pm](https://user-images.githubusercontent.com/6118407/49765358-79df4b80-fc8f-11e8-8191-259a128b1c2f.png)

**Comment by Eworm** [comment]
Yes!
