### ISSUE TITLE
Add ability to check existance of a menu

### ISSUE THREAD

**Issue by elliottregan** [Eworm/big-kahuna#25]
Currently, if a menu used in a template is deleted, the whole site crashes.

Is there already a way to check to see if a menu exists? 

Another option could be to protect a created menu so it isn't accidentally deleted through the CMS.

**Comment by Eworm** [comment]
I published a new release with a check for the actual menu so the site doesn't crash!

**Comment by elliottregan** [comment]
Works great! thanks for the quick update!
