### ISSUE TITLE
Menu changes do not get committed by Spock addon

### ISSUE THREAD

**Issue by elliottregan** [Eworm/big-kahuna#27]
I'm using the Spock addon to manage content, and none of BigKahuna's changes will be staged. After reading Statamic's addon docs, it looks like the issue could be due to one of these:

- A bug in Statamic where `$this->storage->putJSON` does not fire one of the events Spock is listening for https://docs.statamic.com/addons/helpers#storage-put-json
- BigKahuna is not firing the right event for Spock
- something unique about my configuration 

Could be related to this issue: https://github.com/statamic/spock/issues/35

thanks!

**Comment by Eworm** [comment]
BK isn't firing any Statamic events when saving as far as I can see, so it might be related to that: https://docs.statamic.com/addons/events/#main
