### ISSUE TITLE
A Custom URL cannot be the first child of a Pages URL

### ISSUE THREAD

**Issue by elliottregan** [Eworm/big-kahuna#31]
This came about when a client tried creating a Custom URL to link to a hash ID on one of the site's pages, but I can reproducing it with any url, such as `https://github.com`. The BK tag will not render if a Custom URL is the first child of a Pages URL.

## Steps to Reproduce:
**Given:** I have a menu with at least one Pages URL
**When:** I create a menu item with a Custom URL as a child of an existing Pages URL 
**Then:** I expect to be able to reorder it to any index
**BUT:** If the item is the first child of the Pages URL, the site throws this error:
```
FatalThrowableError in BigKahunaTags.php line 105: Call to a member function absoluteUrl() on null
```

### Working Scenario:
![Screen Shot 2019-07-30 at 11 19 51 AM](https://user-images.githubusercontent.com/950202/62151168-eeb5d300-b2bc-11e9-858e-04d774574de8.png)

### Broken Scenario
![Screen Shot 2019-07-30 at 11 19 40 AM](https://user-images.githubusercontent.com/950202/62151177-f6757780-b2bc-11e9-9557-85633a19a500.png)

**Comment by Eworm** [comment]
Thanks for finding this one! I've fixed it and published a new release.
