### ISSUE TITLE
Deleting a page that was in a menu breaks the menu screen

### ISSUE THREAD

**Issue by paulburgess** [Eworm/big-kahuna#36]
Hi, here's an example.

- 'Main menu' screen shows all my pages including a Contact page
- Go to Pages in cp, delete the contact page
- Go back to that 'Main menu' in Menus, whole menu in right column is now blank

Many thanks!

**Comment by paulburgess** [comment]
Now the main template has gone funky - screenshot: https://dlrg.co/25db17f2c291

**Comment by Eworm** [comment]
It may sound silly, but I've never considered this scenario :-) I'll have to add a check.

**Comment by Eworm** [comment]
Fixed!
