### ISSUE TITLE
Error when local absolute url is define

### ISSUE THREAD

**Issue by thisJerem** [Eworm/big-kahuna#38]
Hello,

The plugin has a problem with new version since it saved json data in storage with a key url that will contain the absolute URL website.
When switching between differents env it broke statamic :(
I need actually absolute url for SEO and static cache plugin and other stuff, could you please update big-kahuna to save only relative url ?

![image](https://user-images.githubusercontent.com/1255528/69249839-dc82dc00-0bae-11ea-85de-ff62c7a57c6b.png)

**Comment by Eworm** [comment]
Hi!

I don't understand your question (you need an absolute url but are asking for a relative one?). Please try to make it clearer by explaining what situation you want and what actually happens.

Also: the error you post is about a missing id, which has nothing to do with urls.

**Comment by thisJerem** [comment]
Hi Eworm ! 

Thanks for your quick reply !
First the error on missing ID is not really clear because the ID are set but maybe there is an internal statamic comparaison with the url in the JSON and it failed.
But the error doesn't really help anyway.

In Statamic I have set absolute URL (stored as ENV key) for many reasons like this : 
```
locales:
  fr:
    full: fr_FR
    name: French
    url: '{env:BASEURL}'
```

So with this I have a local alias URL, a staging URL and a prod URL.
But now with the last version of BigKahuna, the menu store a key "url" with absolute value, and as I sync with Spock all environments, my menus-{keys}.json are in conflict with other environment that they where created !

For exemple, my local data menu :
```
{
    "pages": [{
        "id": "-----------------,
        "order": 1,
        "type": "Pages",
        "title": "Accueil",
        "original_title": "Accueil",
        "url": "http:\/\/stl-medical-v2.test\/",
        "classname": "",
        "linktitle": "",
        "items": [],
        "pages": []
    }, {
        "id": "----------------",
        "order": 2,
        "type": "Pages",
        "title": "Nos annonces",
        "original_title": "Nos annonces",
        "url": "http:\/\/stl-medical-v2.test\/annonces",
        "classname": "",
        "linktitle": "",
```
When I set manually url to relative version, without "http:\/\/stl-medical-v2.test\" it work !

**Comment by Eworm** [comment]
I changed the absolute urls to relative ones (this seems like a good idea, I wonder why no one hasn't asked this before)

**Comment by Eworm** [comment]
And I published a new release!

**Comment by thisJerem** [comment]
Thanks you very much !
