### ISSUE TITLE
Active class is not set

### ISSUE THREAD

**Issue by thisJerem** [Eworm/big-kahuna#39]
Hello Eworm !

The last version seems to not set the default active class.
There is no error, but there is no class added when the current URL is one of the item menu.
For example : 
![image](https://user-images.githubusercontent.com/1255528/69617138-12edaa80-1038-11ea-94e1-a3b25a3dd01e.png)
First \<li\> element should have the is--active, but don't.

From code : 
```
{{ big_kahuna 
    menu="menu-principal" 
    class="main-nav text-sm flex lg:flex-row lg:flex-grow"
    item_class="burger-item flex leading-none mt-4 font-medium lg:flex-row lg:mt-0 lg:mr-8"
}}
```

Environment :
- Version 2.2.1
- Local
- Without cache
- Stache enabled

**Comment by Eworm** [comment]
Thanks for reporting the bug! It's fixed, and I'll publish a new release.
