### ISSUE TITLE
Needs some customization options

### ISSUE THREAD

**Issue by Gaslamp** [Eworm/big-kahuna#40]
This app is great.  I would have bought it today if it had a couple more features...
This app needs the ability to customize the wrapper UL elements with custom classes (and submenu UL elements)

At the very least, you should be able to build your own menu templates simply using variables output by this plugin (rather than being required to use the native (and rather restrictive) {{ nav }} tag.

Needs the ability to add carets or icons for dropdown elements. (Or just put them in a custom template or partial)  (You COULD add them as CSS elements, I know, but sometimes you're working with other people's code, so you want to work smarter not harder, and build around what they gave you)

Needs the ability to customize the global LI and submenu UL and LI classes (classes for all menu elements, rather than customizing every menu item individually)  (Or just add them to a custom template or partial)  OR at least bulk edit the classes on the individual elements.

Needs the ability to have the same menu structure with different wrapper (UL and LI) classes.  Some responsive menus require the same menu classed differently in the mobile view.

With just a few tweaks, this could easily be a core-worthy component for Statamic... but it's not QUITE there yet.  Good work getting it this far.

**Comment by MattRogowski** [comment]
I would also like more control over the HTML as I use Tailwind. Ideally I'd like to be able to loop through a list of links, and sub-links.

**Comment by stoffelio** [comment]
No feedback for this? As another tailwind user I would really welcome a manual output option as well.

**Comment by MattRogowski** [comment]
May be a moot point now as Statamic v3 has a navigation builder as a core feature.

**Comment by stoffelio** [comment]
Ah, thanks, wasn't aware of that. Then let's hope that the recent announcement on twitter means that v3 is about to be released ..
