### ISSUE TITLE
Undefined variable: isactive

### ISSUE THREAD

**Issue by rizkysyazuli** [Eworm/big-kahuna#41]
Saw a bunch of these errors on my live site log files. 

```
ErrorException: Undefined variable: isactive
in /var/www/html/blabla/site/addons/BigKahuna/BigKahunaTags.php:79
```

This block of code seems problematic.

```php
if ($content) {
    $isactive = '';
    ...
}
$html .= '<li class="' . $itemClass . $isParent . $isactive . $myClassname . '">'; // line 79
```

The `$isactive` variable doesn't get set somehow. what's the possibility of `$content` being empty/undefined?

This does not break my site though. At least not that i know of. Maybe this error happens on some deeply buried pages somewhere. Not sure. Statamic's log file is not very informative in this case.

I'm running Statamic 2.11.7 and BigKahuna 1.4.5

**Comment by Eworm** [comment]
Is your site online so I can browse it?

**Comment by rizkysyazuli** [comment]
Yeah sure. it's here: https://www.biznetnetworks.com/
But i kinda suppress the error by putting another `$isactive = '';` outside of the if block.
