### ISSUE TITLE
Add option to define target of links

### ISSUE THREAD

**Issue by sebszocinski** [Eworm/big-kahuna#42]
External links should have `target="_blank"` or make it an option.

**Comment by Eworm** [comment]
I really really hate blank targets because they're confusing and just bad practice: https://css-tricks.com/use-target_blank/

**Comment by sebszocinski** [comment]
Thats great, and you're entitled to your own opinion, but why should you decide this for everyone else?
It doesn't hurt you making it an option where the functionality may be justified. I'll update the title.

**Comment by sebszocinski** [comment]
Any updates on this?

**Comment by Eworm** [comment]
This will probably be available in the V3 version where a menu builder is part of the core. So I won't be adding this.
